### ISSUE TITLE
[Add]セットメニューサイト（テンプレ作成）

### ISSUE THREAD

**Issue by 1F10220295-Kota** [konjikun/team-project#11]
セットメニューサイトのテンプレート作成
3種類ぐらい紹介するのかな？それに応じて３つテンプレートを作成（複製）してください
<img width="567" alt="2022-06-23_17h32_07" src="https://user-images.githubusercontent.com/107393944/175254345-98cf442b-e727-4cef-83ad-2986cf9bc464.png">

**Comment by konjikun** [comment]
よろしく

**Comment by konjikun** [comment]
完了
