### ISSUE TITLE
[Add]各チェーン紹介サイト（テンプレ作成）

### ISSUE THREAD

**Issue by 1F10220295-Kota** [konjikun/team-project#5]
各チェーンサイトを新たに作成、またレイアウトの構成作成
・かっぱ寿司
・はま寿司
・くら寿司
・スシロー
・魚べい
以上の５つサイトのテンプレートを作成
<img width="570" alt="image" src="https://user-images.githubusercontent.com/107393944/175250977-530b570a-2849-4997-8db6-08fc3b34d4b8.png">

**Comment by konjikun** [comment]
よろしく
